site:
  name: tuition.danieljsmith.org
  site: 'https://tuition.danieljsmith.org'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: tuition.danieljsmith.org
    template: '%s — tuition.danieljsmith.org'
  description: 'Internationally oriented maths and physics tutor. Cambridge graduate with 1k+ hours experience. Rates starting at £42/hour for A-level, Undergrad, TMUA, STEP and more.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: tuition.danieljsmith.org
    images:
      - url: '~/assets/images/IMG_0978_crop.JPG'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: null
    site: null
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
