site:
  name: danieljsmith.org
  site: 'https://astrowind.vercel.app'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: danieljsmith.org
    template: '%s â€” danieljsmith.org'
  description: "Professional tutoring services tailored to help students achieve their academic goals."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: danieljsmith.org
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: null
    site: null
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
